### ISSUE TITLE
Unable to update to latest BW version - No update needed

### ISSUE THREAD

**Issue by oliverjnash** [jakeswenson/BitBetter#136]
Bitwarden seems to have changed their version numbering so I'm assuming it's related to this. But I'm unable to update from v1.48.1 using the update-bitwarden.sh script as it tells me that 1.48.1 is the latest version. When in reality, there have been a couple of releases since then (the latest being Version 2022.5.1). 

I note the recent pull request relating to version numbers (https://github.com/jakeswenson/BitBetter/pull/135) but not sure if this is related. 

Any pointers you can offer would be greatly appreciated.

**Comment by Ayitaka** [comment]
They have not released the newer version for self-hosted yet, it is still on [1.48.1](https://github.com/bitwarden/self-host/blob/master/version.json). They usually update the self-hosted version one or two weeks after the server version is updated in order to test it on the main Bitwarden server before pushing it out to self-hosted customers.

**Comment by Grommish** [comment]
Not only that, but the endpoint for the build script has changed, and they are going back to internal versioning rather than pulling from a json

But, I did receive a notification regarding https://github.com/bitwarden/server/releases/tag/v2022.5.1
Which is listed as 
```
Note: Only Self-host release

    Config fix from the latest release 2022.05.0
```

I think they mis-tagged it as a self-host update.

**Comment by oliverjnash** [comment]
Thanks guys, much appreciated. Will close this off for now and keep an eye on it over the next week or so.

**Comment by Ayitaka** [comment]
Just following up with an FYI: The self-hosted version was updated about 6 hours ago so go ahead and try it again now. 😀

**Comment by oliverjnash** [comment]
Thanks so much for the heads up @Ayitaka  - that's worked perfectly 😀
