### ISSUE TITLE
made a script for organisation creation

### ISSUE THREAD

**Issue by robina80** [jakeswenson/BitBetter#39]
hi all,

just thought i would share as i think this project is awesome!!!!!!

#!/bin/bash

echo "please enter organisation name":
read name

echo "please enter the owners email of this organisation (user must already exist)":
read owner

echo "please enter company":
read company

read -p "continue (y/n)?" CONT

if [ "$CONT" = "y" ]; then

/bitwarden/bwdata/BitBetter/src/licenseGen/run.sh /bitwarden/bwdata/BitBetter/.keys/cert.pfx org "$name" "$owner" installation-id "$company" >> /license_files/"$name".json

echo "this is the organisational license file" | swaks --to "$owner" --from user@domain.com --server smtp_relay_ip --attach-type /license_files/"$name".json

rm -f /license_files/"$name".json

else
exit
fi

rob

**Comment by JeffAlyanak** [comment]
@robina80 

There is already an [interactive mode for generating licenses](https://github.com/jakeswenson/BitBetter#generating-signed-licenses) that does just that. It can be used for both organization and user licenses.

```
./src/licenseGen/run.sh interactive
```

I assume most users use the interactive mode rather than manually providing all of the parameters themselves but we left the manual mode for those who wish to use a script to automate the creation of many licenses.

**Comment by robina80** [comment]
Yes you are correct

The reason I have made a script is for end users to use it but it's really for emails as every organisation it creates it sends the owner an email and attached is the license.json file

**Comment by sutidor** [comment]
Great idea.

I modified it for my purposes (reading the .env variable for install-id and using mutt instead of swaks)

#!/bin/bash

#install mailutils and mutt if not already done
if [ $(dpkg-query -W -f='${Status}' mailutils 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
  apt install mailutils;
fi

if [ $(dpkg-query -W -f='${Status}' mutt 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
  apt install mutt;
fi

echo "please enter organisation name":
read name

echo "please enter the owners email of this organisation (user must already exist)":
read owner

#echo "please enter company":
#read company
#get InstallID env variable from Bitwarden
source /root/bwdata/env/global.override.env
company=$globalSettings__installation__id

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
./run.sh "$DIR/.keys/cert.pfx" org "$name" "$owner" "$company" >> license_files/"$name".json

echo "this is the organisational license file" | mutt -s "neue Orglizenz für $name" -a $DIR/license_files/"$name".json -- $owner <<< "siehe Anhang"

#dont remove license from Server
#rm -f /license_files/"$name".json

**Comment by robina80** [comment]
Yes I tried mutt or the mail command but swaks is the only one you can the options to use an smtp relay and I need this as my smtp relay is on another host

**Comment by sutidor** [comment]
I got an SSL error when trying to use swaks with your script. Bitwarden gave me one too, I think it's because the wildcard certificate that I use.

**Comment by robina80** [comment]
Mmm... Just used the script now and it's fine

Ohhh do you mean the installation-I'd you used a wildcard ie *

**Comment by sutidor** [comment]
I want to authenticate with smtp server:
swaks --server mail.domain.tld --port 465 -ssl -4 --auth-user no-reply@domain.tld --auth-password xxxYYYzzz --to recipient@otherdomain.tld --from no-reply@domain.tld --attach-type /license_files/myneworg.json

Debian package is not the newest and I dont feel like make install it manually. Maybe I need to use -tlsc instead of -ssl parameter, too.

Because afterall it's only a backend tool I dont refine it any further.

**Comment by robina80** [comment]
mine looks like this, i have amended it - 

swaks --to to@domain.com --from from@domain.com --server smtp-relay-server --body "upload this file in organisations page" --attach-type /license_files/"$name".json

but if you havnt got an internal smtp relay and want to use o365 or gmail use this - 

swaks -t to@domain.com -f from@domain.com -s smtp-relay-server -p 587 -tlso -au username -ap password

think that will work

**Comment by robina80** [comment]
smashed it

swaks -t "$owner" -f someone@gmail.com -s smtp-relay-ip --header "Subject: Bitwarden "$name".json" --body "upload this file in organisations page" --attach-type /license_files/"$name".json -S 2

**Comment by sutidor** [comment]
> mine looks like this, i have amended it -
> 
> swaks --to [to@domain.com](mailto:to@domain.com) --from [from@domain.com](mailto:from@domain.com) --server smtp-relay-server --body "upload this file in organisations page" --attach-type /license_files/"$name".json
> 
> but if you havnt got an internal smtp relay and want to use o365 or gmail use this -
> 
> swaks -t [to@domain.com](mailto:to@domain.com) -f [from@domain.com](mailto:from@domain.com) -s smtp-relay-server -p 587 -tlso -au username -ap password

Hey man, that solution works like a charm. Thanks!!
